### ISSUE TITLE
cool down time on stake event

### ISSUE THREAD

**Issue by eddybounasr** [cardinal-labs/cardinal-staking#205]
-Set up a duration so whenever users stake , they start accumulate after them entry time + duration ... this helps pool amdins running scripts as background job to have time and update pools/multipliers ... with minimum UI changes 

-another timer can be also set for the entire pool , like i created the pool now but i want the staking to start in a specific date for example all users staking will start accumulate in X date.

note : these are two different features . I am interested with the first one thx

**Comment by gchatz22** [comment]
Hey, this is a niche feature that I am not sure it provides great value for stake pool admins and users.

Your concern about admins `running scripts as background job to have time and update pools/multipliers` can be addressed by running their periodic script more frequently thus updating multipliers more accurately.

Adding adding this delay in accumulating rewards for a user seems to be like a bad UX from my perspective since as a staker I would be pretty confused to why I am not accumulating rewards say in the first 10 seconds of my staking.

**Comment by gchatz22** [comment]
Closing as per request
